name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: amd64
            goarch: amd64
          - os: macos-14
            arch: arm64
            goarch: arm64
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Setup build environment
      run: |
        go version
        go env
        pwd
        ls -la
    
    - name: Download dependencies
      run: |
        go mod download
        go mod verify
    
    - name: Build release
      run: |
        mkdir -p dist
        export CGO_ENABLED=1
        export GOOS=darwin
        export GOARCH=${{ matrix.goarch }}
        # Build with explicit module mode
        export GO111MODULE=on
        go build -mod=readonly -v -o dist/macrod-daemon ./cmd/daemon
        go build -mod=readonly -v -o dist/macrod-tui ./cmd/tui
        cd dist && tar -czf macrod-darwin-${{ matrix.arch }}.tar.gz macrod-daemon macrod-tui
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/macrod-darwin-${{ matrix.arch }}.tar.gz
        body: |
          ## Installation
          
          ```bash
          curl -fsSL https://raw.githubusercontent.com/monotykamary/macrod/main/install.sh | bash
          ```
          
          ## Changes in v0.0.2
          
          - Fixed example macros to use static dates for consistent ordering
          - Improved GitHub Actions workflow for releases
          
          See all commits for details.